export const RECURRENCE_CONSTANTS = {
  NOTIFICATION_ADVANCE_MINUTES: 15,
  RECURRENCE_LOOKAHEAD_HOURS: 2,
  RECURRENCE_CHECK_INTERVAL_MINUTES: 15,
  MAX_RECURRENCE_RULE_LENGTH: 500,
  RRULE_PARSE_TIMEOUT_MS: 5000,
  DISTRIBUTED_LOCK_TTL_MS: 90000,
} as const

export const NOTIFICATION_CONSTANTS = {
  DEFAULT_SEND_TIMEOUT_MS: 10000,
  MAX_RETRY_ATTEMPTS: 3,
  RETRY_DELAY_MS: 2000,
  CLEANUP_INTERVAL_HOURS: 24,
} as const

export const WORKER_CONSTANTS = {
  RECURRENCE_WORKER_CONCURRENCY: 2,
  NOTIFICATION_WORKER_CONCURRENCY: 5,
  AI_WORKER_CONCURRENCY: 2,
  JOB_CLEANUP_COMPLETE_COUNT: 100,
  JOB_CLEANUP_FAILED_COUNT: 500,
} as const