"use client"

import { useState, useEffect, useRef } from "react"
import { Label } from "@/components/ui/label"
import { useOnboarding } from "@/contexts/onboarding-context"
import { Sparkles, Loader2, CheckCircle2, AlertCircle } from "lucide-react"
import { motion, AnimatePresence } from "framer-motion"
import { apiClient } from "@/utils/apiClient"

const CHALLENGES = [
  { id: "too_many_meetings", title: "Too many meetings", desc: "Can't find focus time" },
  { id: "forgetting_tasks", title: "Forgetting tasks", desc: "Things slip through" },
  { id: "work_life_balance", title: "Work-life balance", desc: "Struggling to disconnect" },
  { id: "scheduling_conflicts", title: "Scheduling conflicts", desc: "Double bookings" },
  { id: "none", title: "None of the above", desc: "Just want to be organized" },
]

const BUFFER_PREFERENCES = [
  { id: "back_to_back", title: "Back-to-back", desc: "Maximize efficiency" },
  { id: "buffer_time", title: "Buffer time", desc: "5-10 min between tasks" },
  { id: "flexible", title: "Flexible", desc: "AI decides based on context" },
]

export function StepAISetup() {
  const { collectedData, updateData } = useOnboarding()
  const [challenge, setChallenge] = useState(collectedData.challenge || "")
  const [bufferPreference, setBufferPreference] = useState(collectedData.buffer_preference || "flexible")
  const [isGenerating, setIsGenerating] = useState(false)
  const [generatedRoutines, setGeneratedRoutines] = useState<any[]>(collectedData.generated_routines || [])
  const [selectedRoutineIndex, setSelectedRoutineIndex] = useState<number>(0)
  const [error, setError] = useState<string | null>(null)
  const [isFallback, setIsFallback] = useState(false)
  const [isAccepted, setIsAccepted] = useState(Boolean(collectedData.accepted_routine && collectedData.challenge !== undefined))
  const hasAutoGenerated = useRef(Boolean(collectedData.generated_routines?.length))

  const handleGenerateRoutine = async () => {
    setIsGenerating(true)
    setError(null)
    setIsAccepted(false)
    
    try {
      const data = await apiClient.onboarding.generateRoutine({
        ...collectedData,
        challenge,
      })
      setGeneratedRoutines(data.data)
      setIsFallback(data.fallback || false)
    } catch (err) {
      setError('Failed to generate routine. Please try again.')
    } finally {
      setIsGenerating(false)
    }
  }

  const handleAccept = () => {
    updateData({
      challenge,
      buffer_preference: bufferPreference,
      generated_routines: generatedRoutines,
      accepted_routine: generatedRoutines[selectedRoutineIndex],
    })
    setIsAccepted(true)
  }

  const handleRegenerate = () => {
    setGeneratedRoutines([])
    updateData({ generated_routines: [], accepted_routine: undefined })
    handleGenerateRoutine()
  }

  useEffect(() => {
    if (!hasAutoGenerated.current && !generatedRoutines.length && !isGenerating) {
      hasAutoGenerated.current = true
      handleGenerateRoutine()
    }
  }, [])

  return (
    <div className="space-y-8">
      {/* Challenge Selection */}
      <div className="space-y-3">
        <Label className="text-xs uppercase tracking-wider text-muted-foreground font-semibold">
          What's your biggest scheduling challenge?
        </Label>
        <div className="grid grid-cols-1 gap-2">
          {CHALLENGES.map((item) => (
            <button
              key={item.id}
              onClick={() => setChallenge(item.id)}
              className={`flex items-center gap-3 text-left p-3 rounded-xl border transition-all ${
                challenge === item.id
                  ? "bg-primary/10 border-primary text-primary"
                  : "bg-background border-border/50 hover:border-border text-foreground"
              }`}
            >
              <div className={`w-5 h-5 rounded-full border-2 flex items-center justify-center ${
                challenge === item.id ? "border-primary bg-primary" : "border-border"
              }`}>
                {challenge === item.id && <CheckCircle2 size={12} className="text-primary-foreground" />}
              </div>
              <div>
                <span className="font-semibold text-sm block">{item.title}</span>
                <span className={`text-xs mt-0.5 block ${challenge === item.id ? "text-primary/70" : "text-muted-foreground"}`}>
                  {item.desc}
                </span>
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* Buffer Preference */}
      <div className="space-y-3">
        <Label className="text-xs uppercase tracking-wider text-muted-foreground font-semibold">
          Task Spacing Preference
        </Label>
        <div className="grid grid-cols-1 gap-2">
          {BUFFER_PREFERENCES.map((item) => (
            <button
              key={item.id}
              onClick={() => setBufferPreference(item.id)}
              className={`flex items-center gap-3 text-left p-3 rounded-xl border transition-all ${
                bufferPreference === item.id
                  ? "bg-primary/10 border-primary text-primary"
                  : "bg-background border-border/50 hover:border-border text-foreground"
              }`}
            >
              <div className={`w-5 h-5 rounded-full border-2 flex items-center justify-center ${
                bufferPreference === item.id ? "border-primary bg-primary" : "border-border"
              }`}>
                {bufferPreference === item.id && <CheckCircle2 size={12} className="text-primary-foreground" />}
              </div>
              <div>
                <span className="font-semibold text-sm block">{item.title}</span>
                <span className={`text-xs mt-0.5 block ${bufferPreference === item.id ? "text-primary/70" : "text-muted-foreground"}`}>
                  {item.desc}
                </span>
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* AI Generation Status */}
      <div className="space-y-4">
        <Label className="text-xs uppercase tracking-wider text-muted-foreground font-semibold">
          Select Your Default Routine
        </Label>

        {isGenerating && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="p-4 bg-muted/50 rounded-xl border border-border/50"
          >
            <div className="flex items-center gap-3">
              <Loader2 className="w-5 h-5 animate-spin text-primary" />
              <div>
                <span className="font-semibold text-sm">Generating personalized routines...</span>
                <span className="text-xs text-muted-foreground block mt-1">
                  AI is analyzing your preferences to create your daily blueprints
                </span>
              </div>
            </div>
          </motion.div>
        )}

        {error && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="p-4 bg-destructive/10 rounded-xl border border-destructive/20"
          >
            <div className="flex items-center gap-3">
              <AlertCircle className="w-5 h-5 text-destructive" />
              <div>
                <span className="font-semibold text-sm text-destructive">Generation Failed</span>
                <span className="text-xs text-destructive/80 block mt-1">{error}</span>
              </div>
            </div>
          </motion.div>
        )}

        {generatedRoutines.length > 0 && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-4"
          >
            <div className="flex items-center gap-2 mb-2">
              <Sparkles className="w-4 h-4 text-primary" />
              <span className="font-semibold text-sm">
                Choose the best fit for your workflow
              </span>
              {isFallback && (
                <span className="text-xs text-muted-foreground">(Template-based)</span>
              )}
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
              {generatedRoutines.map((routine, index) => (
                <motion.div
                  key={index}
                  onClick={() => setSelectedRoutineIndex(index)}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: index * 0.1 }}
                  className={`p-4 rounded-xl border cursor-pointer transition-all ${
                    selectedRoutineIndex === index
                      ? "bg-primary/5 border-primary shadow-sm"
                      : "bg-background border-border/50 hover:border-border"
                  }`}
                >
                  <div className="flex flex-col h-full">
                    <div className="flex items-start justify-between gap-2 mb-2">
                      <div className="flex-1">
                        <span className="font-bold text-sm block" style={{ color: routine.color }}>{routine.title}</span>
                        <span className="text-xs text-muted-foreground mt-1 block leading-tight">{routine.goal}</span>
                      </div>
                      <div className={`w-4 h-4 rounded-full border-2 flex items-center justify-center shrink-0 ${
                        selectedRoutineIndex === index ? "border-primary bg-primary" : "border-border"
                      }`}>
                        {selectedRoutineIndex === index && <CheckCircle2 size={10} className="text-primary-foreground" />}
                      </div>
                    </div>
                    
                    <div className="mt-auto pt-3 space-y-1.5 border-t border-border/30">
                      <span className="text-[10px] uppercase font-bold text-muted-foreground">Key Tasks</span>
                      {routine.tasks.slice(0, 3).map((task: any, tIdx: number) => (
                        <div key={tIdx} className="flex items-center gap-1.5">
                          <div className={`w-1 h-1 rounded-full ${
                            task.priority === 'critical' ? 'bg-destructive' :
                            task.priority === 'high' ? 'bg-orange-500' :
                            task.priority === 'medium' ? 'bg-yellow-500' :
                            'bg-green-500'
                          }`} />
                          <span className="text-xs truncate" title={task.title}>{task.title}</span>
                          <span className="text-[10px] text-muted-foreground ml-auto shrink-0">{task.estimated_duration_minutes}m</span>
                        </div>
                      ))}
                      {routine.tasks.length > 3 && (
                        <div className="text-[10px] text-muted-foreground italic mt-1">
                          + {routine.tasks.length - 3} more tasks
                        </div>
                      )}
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>

            <div className="flex gap-2 mt-4">
              <button
                onClick={handleRegenerate}
                disabled={isGenerating}
                className="flex-1 p-3 bg-background border border-border/50 rounded-xl text-sm font-semibold hover:border-border transition-all"
              >
                Regenerate Options
              </button>
              <button
                onClick={handleAccept}
                disabled={isAccepted || generatedRoutines.length === 0}
                className="flex-[2] p-3 bg-primary text-primary-foreground rounded-xl text-sm font-semibold hover:bg-primary/90 transition-all disabled:opacity-70"
              >
                {isAccepted ? "Routine Accepted" : "Set as Default Routine"}
              </button>
            </div>
          </motion.div>
        )}
      </div>
    </div>
  )
}
