export const KEYBINDINGS = {
    GLOBAL: {
        NEW_TASK: ['/'],
        GO_TO_DASHBOARD: ['g d'],
        GO_TO_TASKS: ['g t'],
        GO_TO_CALENDAR: ['g c'],
        GO_TO_SETTINGS: ['g s'],
        GO_To_INBOX: ['g i'],
        COMMAND_PALETTE: ['Meta+k', 'Control+k'],
        SHOW_HELP: ['?'],
    },
    TASK_BOARD: {
        NAV_UP: ['ArrowUp', 'ArrowLeft', 'k'],
        NAV_DOWN: ['ArrowDown', 'ArrowRight', 'j'],
        MOVE_LEFT: ['Shift+ArrowLeft', 'Shift+H'],
        MOVE_RIGHT: ['Shift+ArrowRight', 'Shift+L'],
        EDIT_TASK: ['Enter', 'e'],
        TOGGLE_COMPLETE: [' '], // Space only
        DESELECT: ['Escape'],
        BULK_SELECT: ['Shift+Space'],
        SET_PRIORITY_CRITICAL: ['1'],
        SET_PRIORITY_HIGH: ['2'],
        SET_PRIORITY_MEDIUM: ['3'],
        SET_PRIORITY_LOW: ['4'],
        DELETE_TASK: ['d'],
        EXPAND_SUBTASKS: ['>'],
        COLLAPSE_SUBTASKS: ['<'],
        ADD_SUBTASK: ['s'],
        COMPLETE_SUBTASKS: ['Shift+Space'],
    },
    CALENDAR: {
        NAV_UP: ['ArrowUp', 'ArrowLeft', 'k'],
        NAV_DOWN: ['ArrowDown', 'ArrowRight', 'j'],
        EDIT_EVENT: ['Enter'],
        DESELECT: ['Escape'],
        VIEW_MONTH: ['Alt+3'],
        VIEW_WEEK: ['Alt+2'],
        VIEW_DAY: ['Alt+1'],
        TOGGLE_PANEL: ['Alt+w', 'w'],
    },
    TIMEBLOCK: {
        CREATE_BLOCK: ['t', 'b'],
        NAV_LEFT: ['Shift+h'],
        NAV_RIGHT: ['Shift+l'],
        RESIZE_START: ['['],
        RESIZE_END: [']'],
        DELETE_BLOCK: ['d'],
        CONVERT_TO_TASK: ['c'],
    },
    TEMPLATES: {
        OPEN_LIBRARY: ['t', 'l'],
        QUICK_APPLY: ['t', 'a'],
        CREATE_FROM_TASK: ['t', 'n'],
    },
    MODALS: {
        CLOSE: ['Escape'],
        SAVE: ['Meta+Enter', 'Control+Enter'],
        NAV_DOWN: ['ArrowDown', 'Control+j'],
        NAV_UP: ['ArrowUp', 'Control+k'],
        SELECT_OPTION: ['Enter', 'Tab'],
        SELECT_AND_SAVE_OPTION: ['Enter'],
    }
}
