export const KEYBINDINGS = {
    GLOBAL: {
        NEW_TASK: ['/'],
        GO_TO_DASHBOARD: ['g d'],
        GO_TO_TASKS: ['g t'],
        GO_TO_CALENDAR: ['g c'],
        GO_TO_SETTINGS: ['g s'],
        GO_TO_INBOX: ['g i'],
        GO_TO_TEMPLATES: ['g l'],
        COMMAND_PALETTE: ['Meta+k', 'Control+k'],
        SHOW_HELP: ['?'],
    },
    TASK_BOARD: {
        NAV_UP: ['ArrowUp', 'ArrowLeft', 'k'],
        NAV_DOWN: ['ArrowDown', 'ArrowRight', 'j'],
        SHIFT_SELECT_UP: ['Shift+ArrowUp'],
        SHIFT_SELECT_DOWN: ['Shift+ArrowDown'],
        EDIT_TASK: ['Enter', 'e'],
        TOGGLE_COMPLETE: [' '], // Space only
        DESELECT: ['Escape'],
        BULK_SELECT: ['Shift+Space'],
        SET_STATUS_TODO: ['Shift+1'],
        SET_STATUS_OVERDUE: ['Shift+2'],
        SET_STATUS_DOING: ['Shift+3'],
        SET_PRIORITY_CRITICAL: ['1'],
        SET_PRIORITY_HIGH: ['2'],
        SET_PRIORITY_MEDIUM: ['3'],
        SET_PRIORITY_LOW: ['4'],
        SET_TIME_LOCK: ['l'],
        UNSCHEDULE: ['u'],
        DELETE_TASK: ['d'],
        EXPAND_SUBTASKS: ['>'],
        COLLAPSE_SUBTASKS: ['<'],
        ADD_SUBTASK: ['s'],
    },
    CALENDAR: {
        NAV_UP: ['ArrowUp', 'ArrowLeft', 'k'],
        NAV_DOWN: ['ArrowDown', 'ArrowRight', 'j'],
        EDIT_EVENT: ['Enter'],
        DESELECT: ['Escape'],
        VIEW_MONTH: ['Alt+3'],
        VIEW_WEEK: ['Alt+2'],
        VIEW_DAY: ['Alt+1'],
        TOGGLE_PANEL: ['Alt+w', 'w'],
        UNSCHEDULE: ['u'],
    },
    TIMEBLOCK: {
        CREATE_BLOCK: ['t', 'b'],
    },
    TEMPLATES: {
        OPEN_LIBRARY: ['t', 'l'],
        QUICK_APPLY: ['t', 'a'],
        CREATE_FROM_TASK: ['t', 'n'],
    },
    MODALS: {
        CLOSE: ['Escape'],
        SAVE: ['Meta+Enter', 'Control+Enter'],
        NAV_DOWN: ['ArrowDown', 'Control+j'],
        NAV_UP: ['ArrowUp', 'Control+k'],
        SELECT_OPTION: ['Enter', 'Tab'],
        SELECT_AND_SAVE_OPTION: ['Enter'],
    }
}
